version: 2

before:
  hooks:
    # Build WASM plugins before binary compilation
    - make -C plugins/file build
    - make -C plugins/command build
    - make -C plugins/http build
    - make -C plugins/dns build
    - make -C plugins/tcp build
    - make -C plugins/smtp build

builds:
  - id: reglet
    main: ./cmd/reglet
    binary: reglet
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/whiskeyjimbo/reglet/internal/infrastructure/build.Version={{.Version}}
      - -X github.com/whiskeyjimbo/reglet/internal/infrastructure/build.Commit={{.Commit}}
      - -X github.com/whiskeyjimbo/reglet/internal/infrastructure/build.BuildDate={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: reglet-archive
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "reglet-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - docs/examples/*.yaml
      - docs/examples/README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*feat(\(.+\))?(!)?\:\s.*$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix(\(.+\))?(!)?\:\s.*$'
      order: 1
    - title: Documentation
      regexp: '^.*docs(\(.+\))?\:\s.*$'
      order: 2
    - title: Performance
      regexp: '^.*perf(\(.+\))?\:\s.*$'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: whiskeyjimbo
    name: reglet
  prerelease: auto
  mode: replace
  draft: false
  name_template: "Reglet {{.Tag}}"
  header: |
    ## Reglet {{ .Tag }}

    Infrastructure compliance validation with WASM plugins.

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install whiskeyjimbo/tap/reglet
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/whiskeyjimbo/reglet:{{ .Tag }}
    ```

    **Manual Download:**
    Download the appropriate archive for your platform below, extract and move to your PATH.

# Homebrew tap
brews:
  - repository:
      owner: whiskeyjimbo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/whiskeyjimbo/reglet
    description: "Compliance as Code - Infrastructure validation with WASM plugins"
    license: "Apache-2.0"
    skip_upload: auto
    test: |
      system "#{bin}/reglet", "--version"
    install: |
      bin.install "reglet"
      (pkgshare/"examples").install Dir["docs/examples/*"]

# Container images using ko (distroless)
kos:
  - id: reglet-ko
    build: reglet
    image_refs:
      - '{{ .ProjectName }}-{{.Arch}}'
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}{{.Major}}.{{.Minor}}{{ end }}'
      - '{{ if not .Prerelease }}latest{{ end }}'
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: spdx
    labels:
      org.opencontainers.image.title: Reglet
      org.opencontainers.image.description: Compliance as Code - Infrastructure validation with WASM plugins
      org.opencontainers.image.url: https://github.com/whiskeyjimbo/reglet
      org.opencontainers.image.source: https://github.com/whiskeyjimbo/reglet
      org.opencontainers.image.version: '{{.Version}}'
      org.opencontainers.image.created: '{{.Date}}'
      org.opencontainers.image.revision: '{{.FullCommit}}'
      org.opencontainers.image.licenses: Apache-2.0

# SBOMs for binaries
sboms:
  - id: archive-sbom
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"

# Announce (optional - can enable later)
# announce:
#   skip: '{{gt .Patch 0}}'
#   discord:
#     enabled: true
#     message_template: 'Reglet {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
