name: Feature Request
description: Suggest an idea or enhancement for Reglet
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to accomplish... but I can't because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I'd like Reglet to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: I've tried... but it doesn't work because...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Core engine
        - Plugin system
        - Output formats
        - Security/Capabilities
        - CLI/UX
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        I'm working on... and this feature would allow me to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Configuration or Usage
      description: If applicable, provide an example of how you'd use this feature
      placeholder: |
        ```yaml
        # Example profile using new feature
        ```
      render: yaml

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can provide more details if needed

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or related issues
      placeholder: Related to #123, similar to feature in...
