package scaffold

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// configTemplate is the template for the system config YAML.
const configTemplate = `# System configuration generated by reglet init
# This grants capabilities required for the example controls

capabilities:
{{- range .Capabilities }}
  - kind: {{ .Kind }}
    pattern: "{{ .Pattern }}"
{{- end }}
`

// ConfigGenerator generates system configuration YAML content.
type ConfigGenerator struct{}

// NewConfigGenerator creates a new ConfigGenerator.
func NewConfigGenerator() *ConfigGenerator {
	return &ConfigGenerator{}
}

// generateConfigYAML creates the config YAML content for the given plugins.
func (g *ProfileGenerator) generateConfigYAML(plugins []string) ([]byte, error) {
	capabilities := GetCapabilitiesForPlugins(plugins)
	if len(capabilities) == 0 {
		return nil, fmt.Errorf("no capabilities found for selected plugins")
	}

	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing config template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, map[string]any{
		"Capabilities": capabilities,
	})
	if err != nil {
		return nil, fmt.Errorf("executing config template: %w", err)
	}

	return buf.Bytes(), nil
}

// Generate creates config content for the given plugins.
func (cg *ConfigGenerator) Generate(plugins []string) ([]byte, error) {
	capabilities := GetCapabilitiesForPlugins(plugins)
	if len(capabilities) == 0 {
		return nil, fmt.Errorf("no capabilities found for selected plugins")
	}

	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing config template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, map[string]any{
		"Capabilities": capabilities,
	})
	if err != nil {
		return nil, fmt.Errorf("executing config template: %w", err)
	}

	return buf.Bytes(), nil
}

// ExpandConfigPath expands ~ in the config path to the user's home directory.
func ExpandConfigPath(path string) (string, error) {
	if !strings.HasPrefix(path, "~/") && path != "~" {
		return path, nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}

	if path == "~" {
		return home, nil
	}

	return filepath.Join(home, path[2:]), nil
}

// EnsureConfigDir creates the config directory if it doesn't exist.
func EnsureConfigDir(configPath string) error {
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0o750); err != nil { //nolint:gosec // 0750 is intentionally permissive for user config directory
		return fmt.Errorf("creating config directory: %w", err)
	}
	return nil
}
