package scaffold

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// ProfileGenerator generates profile YAML content from InitOptions.
type ProfileGenerator struct{}

// NewProfileGenerator creates a new ProfileGenerator.
func NewProfileGenerator() *ProfileGenerator {
	return &ProfileGenerator{}
}

// GeneratedProfile holds the result of profile generation.
type GeneratedProfile struct {
	// ProfilePath is the target output path for the profile
	ProfilePath string

	// ConfigPath is the target output path for the config (empty if not generated)
	ConfigPath string

	// ProfileContent is the raw YAML content of the generated profile
	ProfileContent []byte

	// ConfigContent is the raw YAML content of the config (nil if not generated)
	ConfigContent []byte
}

// profileTemplate is the main profile YAML template.
const profileTemplate = `# Profile generated by reglet init
# Edit this file to customize your compliance checks

profile:
  name: {{ .Name }}
  version: 1.0.0
  description: "Profile generated by reglet init"

plugins:
{{- range .Plugins }}
  - {{ . }}
{{- end }}

controls:
  defaults:
    severity: medium

  items:
{{ .ControlsYAML }}`

// controlTemplate is the template for a single control.
const controlTemplate = `    # {{ .Description }}
    - id: {{ .ControlID }}
      name: {{ .ControlName }}
      description: {{ .Description }}
      observations:
        - plugin: {{ .PluginName }}
          config:
            {{ .ConfigIndented }}
          expect:
{{- range .ExpectExpressions }}
            - {{ . }}
{{- end }}
`

// Generate creates profile content from the provided options.
// Returns an error if options are invalid or template execution fails.
func (g *ProfileGenerator) Generate(opts *InitOptions) (*GeneratedProfile, error) {
	if err := opts.Validate(); err != nil {
		return nil, fmt.Errorf("invalid options: %w", err)
	}

	profileContent, err := g.generateProfileYAML(opts)
	if err != nil {
		return nil, fmt.Errorf("generating profile: %w", err)
	}

	result := &GeneratedProfile{
		ProfileContent: profileContent,
		ProfilePath:    opts.OutputPath,
	}

	if opts.WithConfig {
		configContent, err := g.generateConfigYAML(opts.Plugins)
		if err != nil {
			return nil, fmt.Errorf("generating config: %w", err)
		}
		result.ConfigContent = configContent
		result.ConfigPath = DefaultConfigPath()
	}

	return result, nil
}

// generateProfileYAML creates the profile YAML content.
func (g *ProfileGenerator) generateProfileYAML(opts *InitOptions) ([]byte, error) {
	// First, generate controls YAML for all selected plugins
	controlsYAML, err := g.generateControlsYAML(opts.Plugins)
	if err != nil {
		return nil, err
	}

	// Then, render the main profile template
	tmpl, err := template.New("profile").Parse(profileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing profile template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, map[string]any{
		"Name":         opts.ProfileName,
		"Plugins":      opts.Plugins,
		"ControlsYAML": controlsYAML,
	})
	if err != nil {
		return nil, fmt.Errorf("executing profile template: %w", err)
	}

	return buf.Bytes(), nil
}

// generateControlsYAML creates the controls section for all selected plugins.
func (g *ProfileGenerator) generateControlsYAML(plugins []string) (string, error) {
	examples := GetPluginExamples(plugins)
	if len(examples) == 0 {
		return "", fmt.Errorf("no plugin examples found for selected plugins")
	}

	tmpl, err := template.New("control").Parse(controlTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing control template: %w", err)
	}

	var builder strings.Builder
	for i, example := range examples {
		// Add blank line between controls
		if i > 0 {
			builder.WriteString("\n")
		}

		var buf bytes.Buffer
		err = tmpl.Execute(&buf, map[string]any{
			"PluginName":        example.PluginName,
			"ControlID":         example.ControlID,
			"ControlName":       example.ControlName,
			"Description":       example.Description,
			"ConfigIndented":    indentMultiline(example.ConfigYAML, "            "),
			"ExpectExpressions": example.ExpectExpressions,
		})
		if err != nil {
			return "", fmt.Errorf("executing control template for %s: %w", example.PluginName, err)
		}
		builder.Write(buf.Bytes())
	}

	return builder.String(), nil
}

// indentMultiline indents all lines after the first with the given prefix.
func indentMultiline(s string, indent string) string {
	lines := strings.Split(s, "\n")
	if len(lines) <= 1 {
		return s
	}
	for i := 1; i < len(lines); i++ {
		lines[i] = indent + lines[i]
	}
	return strings.Join(lines, "\n")
}
